yunying:
  database:
    url: jdbc:mysql://localhost:3306/yunying?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  zookeeper:
    connect-string: localhost:2181
