server:
  port: 8080
spring:
  application:
    name: YunYing-Server
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/yunying?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${yunying.database.username}
    password: ${yunying.database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    zhipuai:
      base-url: ${yunying.ai.zhipu.base-url}
      api-key: ${yunying.ai.zhipu.api-key}
      chat:
        options:
          model: glm-4-flash
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE

milvus:
  host: ${yunying.milvus.host}
  port: ${yunying.milvus.port}


mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto