server:
  port: 8083
spring:
  application:
    name: yunying-gh
  profiles:
    active: dev

  datasource:
    url: ${yunying.datasource.url}
    username: ${yunying.datasource.username}
    password: ${yunying.datasource.password}
    driver-class-name: ${yunying.datasource.driver-class-name}


  cloud:
    zookeeper:
      connect-string: ${yunying.zookeeper.connect-string} # ?????ZooKeeper??
      discovery:
        enabled: true
      config:
        enabled: true
        root: /config # ?????

github:
  token: ${yunying.github.token} # ?????GitHub Token




mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true




