yunying:
  datasource:
    url: jdbc:mysql://localhost:3306/yunying?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 20040217
    driver-class-name: com.mysql.cj.jdbc.Driver
  zookeeper:
    connect-string: localhost:2181

  elasticsearch:
    uris: http://localhost:9200

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 20040217
    virtual-host: /

  github:
    token: