yunying:
  ai:
    zhipu:
      base-url: https://open.bigmodel.cn/api/paas/
      api-key: 7ec775e28bc3e1a6ebffcf3a4c632ee3.ENPC9Hj2PDyJy2oN
    milvus:
      host: localhost
      port: 19530
      username: root
      password: milvus
  zookeeper:
    connect-string: localhost:2181

  milvus:
    host: localhost
    port: 19530