server:
  port: 8081
spring:
  application:
    name: yunying-ai
  profiles:
    active: dev
  ai:
    zhipuai:
      base-url: ${yunying.ai.zhipu.base-url}
      api-key: ${yunying.ai.zhipu.api-key}
      chat:
        options:
          model: glm-4-flash
    vectorstore:
      milvus:
        client:
          host: ${yunying.ai.milvus.host}
          port: ${yunying.ai.milvus.port}
          username: ${yunying.ai.milvus.username}
          password: ${yunying.ai.milvus.password}
        databaseName: default
        collectionName: vector_store
        embeddingDimension: 1024
        indexType: IVF_FLAT
        metricType: COSINE
  cloud:
    zookeeper:
      connect-string: ${yunying.zookeeper.connect-string} # 替换为你的ZooKeeper地址
      discovery:
        enabled: true
      config:
        enabled: true
        root: /config # 配置根路径
#    sentinel:
#      transport:
#        dashboard: localhost:8858



#
#logging:
#  level:
#    com.yunying: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"

milvus:
  host: ${yunying.milvus.host}
  port: ${yunying.milvus.port}
#  username: ${yunying.milvus.username}
#  password: ${yunying.milvus.password}

